### ISSUE TITLE
Blocs over my head in the Water Reflection

### ISSUE THREAD

**Issue by 1GodRage** [mateuskreuch/minecraft-miniature-shader#1]
**Describe the bug**
Blocs over my head in the Water Reflection.

**To Reproduce**
Go to the lake or the beach.
Place few blocks above your head,
Step back and get amazed.

**Expected behavior**

**Screenshots**

**System Information**
- windows 10, playing 1.20.4 with experimental features on a Purpur server
![image](https://github.com/mateuskreuch/minecraft-miniature-shader/assets/63362446/ebf235fb-5d6f-444a-a14d-7c04bccf7a53)
- Shader version: latest one from Modrinth
- GPU nvidia RTX 
![image](https://github.com/mateuskreuch/minecraft-miniature-shader/assets/63362446/73d156ad-5ce5-4a60-9356-ec5ac490acf3)

**Additional context**
Here is the problem:
![image](https://github.com/mateuskreuch/minecraft-miniature-shader/assets/63362446/4db81c77-26fa-44ca-98ce-25ff532bfd55)
Same withtout any texture pack: 
![image](https://github.com/mateuskreuch/minecraft-miniature-shader/assets/63362446/3588a7c4-50bf-407c-aa3a-27e4f74526d5)
if i jump, it gives headache because it's moving strange.
I made a short video: https://www.youtube.com/watch?v=LHZnAYKGS6o

**Comment by mateuskreuch** [comment]
Unfortunately, that is just an artifact of Screen Space Reflections. In my opinion, the usual way to hide these artifacts is way more distracting, so it'll stay this way.

**Comment by mateuskreuch** [comment]
Example of "fix" from BSL shaders:

![image_2023-12-27_110657448](https://github.com/mateuskreuch/minecraft-miniature-shader/assets/125627070/afd0da9a-8e76-45a0-9806-a55d8513f4da)
