### ISSUE TITLE
Option to turn off flat lighting to mobs/entities/block entities

### ISSUE THREAD

**Issue by 0S3R** [mateuskreuch/minecraft-miniature-shader#12]
it would be nice to have the option to turn off the flat lighting to mobs/entities/block entities

**Comment by mateuskreuch** [comment]
I don't know what you mean.

**Comment by 0S3R** [comment]
![Screenshot (2763)](https://github.com/mateuskreuch/minecraft-miniature-shader/assets/161251194/9396faa1-266c-4fcb-aaa5-26c4076beb4c)
sorry for not clarifying, mobs and block entities still look flat when you turn off 'use flat lighting'

![Screenshot (2766)](https://github.com/mateuskreuch/minecraft-miniature-shader/assets/161251194/06077507-8a6a-40e3-9cc2-29d136b3ab7b)
![Screenshot (2771)](https://github.com/mateuskreuch/minecraft-miniature-shader/assets/161251194/86616068-c180-4db2-9929-c171c432b04f)

**Comment by mateuskreuch** [comment]
I'm afraid there's nothing I can do. 'Use flat lighting' simply enables an Optifine setting (and is only there for Iris users without access to it). If it doesn't include entities as well then that's a preference of the Optifine/Iris developers.
