### ISSUE TITLE
Shadows Broken on 2.8?

### ISSUE THREAD

**Issue by NolanHewitt** [mateuskreuch/minecraft-miniature-shader#14]
Something seemed to happen to shadows in 2.8, [Here is](https://imgur.com/a/mfVv3F4) what it looked like in 2.7, [here is](https://imgur.com/a/77Kyr5a) what it looks in 2.8 with shadows off, [here is ](https://imgur.com/a/ddojGgK) what it looks like with shadows on in 2.8; instead of adding shadows, it just makes everything darker. In-fact [it looks like](https://imgur.com/a/rd5DFF5) shadows are inversed?

**Comment by mateuskreuch** [comment]
Unfortunately, the jump from 2.7 to 2.8 requires resetting your shader settings.

**Comment by NolanHewitt** [comment]
Ah ok I see, the sun lighting slider behaves very differently now. Thank you.

**Comment by NolanHewitt** [comment]
Actually, even with a reset of the shader settings and using default settings, light sources during the night make weird inverse shadows when in view of the moon starting around 8pm in game time.
![huge_2024-03-14_01 44 11](https://github.com/mateuskreuch/minecraft-miniature-shader/assets/52480898/a1367a44-b4ab-474d-862a-520bb5f18958)

**Comment by mateuskreuch** [comment]
Yes, this was fixed in 2.9.
