### ISSUE TITLE
incompatibility with custom items

### ISSUE THREAD

**Issue by deishoke** [mateuskreuch/minecraft-miniature-shader#15]
**Describe the bug**
This shader incompatible with the resource packs with custom items

**Screenshots**
![image](https://github.com/mateuskreuch/minecraft-miniature-shader/assets/121753394/7976a642-e651-4da1-9207-d894387882a7)

**System Information**
- Minecraft version, resource packs, mods, etc - 1.20.1 RP-KSEPSP
- Shader version - 2.9.1
- GPU-Nvidia GTX 1650

**Comment by mateuskreuch** [comment]
Can you provide the resource pack?

**Comment by deishoke** [comment]
https://www.planetminecraft.com/texture-pack/ksepsp-v9-optifine-cit/

**Comment by mateuskreuch** [comment]
Since the screenshot shows no fog, and I couldn't reproduce it at the time, I'll assume this is related to a bug on Sodium Extra (#23), not Miniature.
