### ISSUE TITLE
Shader is not lightweight

### ISSUE THREAD

**Issue by DDAN-17** [mateuskreuch/minecraft-miniature-shader#16]
**Describe the bug**
I am running this shader on Lunar Client v1.20.6 on a MacBook Pro (Retina, 15-inch, Mid 2015) with a 2.5 GHz Quad-Core Intel Core i7 CPU, a Intel Iris Pro 1536 MB graphics card and 16 GB of 1600 MHz DDR3 memory. I originally (without this shader) ran minecraft at about 57 FPS when in a mine next to a torch and water. With the shader, in the same area, I got 12 FPS with a unmodified normal profile, and 17 FPS with a light profile.

**To Reproduce**
Run the shader with a bad computer.

**Expected behavior**
I expected my FPS to not drop much.

**System Information**
- Lunar Client v1.20.6
- Miniature Shader v2.9.1
- MacBook Pro (Retina, 15-inch, Mid 2015)
- 2.5 GHz Quad-Core Intel Core i7
- 16 GB 1600 MHz DDR3
- Intel Iris Pro 1536 MB

**Additional context**
I did also have a lot of other apps open, so that might be adding to the problem.

**Comment by scrahe** [comment]
UPDATE: I just ran the shader with nothing open; I got the same framerate.

**Comment by mateuskreuch** [comment]
I hope you can understand that that is very relative. It would be helpful if you were to compare it to other shaders or earlier versions of Miniature, to see if they run better. Something like:

- Complementary Shaders at 'very low' preset (it's faster than you'd think)
- MakeUp shaders at 'low' preset
- Miniature Shader 2.0

If they all run poorly, then there's likely nothing I can do.

**Comment by mateuskreuch** [comment]
Closing, as no further information was provided.
