### ISSUE TITLE
Stained glass and tinted glass produces no shadows

### ISSUE THREAD

**Issue by MrBrose** [mateuskreuch/minecraft-miniature-shader#20]
Stained glass and tinted glass produces no shadows

![2024-07-06_15 34 03](https://github.com/mateuskreuch/minecraft-miniature-shader/assets/62758046/ec4b05d0-ca83-41ed-a5da-1e6f005645a2)

**Comment by mateuskreuch** [comment]
There's not a good way to go about this. Either stained glass produces a full, opaque shadow, like any other full block, or it produces no shadow. Since it's glass, I chose no shadow...
