### ISSUE TITLE
the game crashes when opening a menu with an entity

### ISSUE THREAD

**Issue by Pinklion6318** [mateuskreuch/minecraft-miniature-shader#21]
**Describe the bug**
the game will crash when a menu with an entity is opened for example the inventory has the player as an entity in the menu
**To Reproduce**
1. open a world
2. make sure entity shadows are on
3. Click on 'press [E]'

i dont know if it is with entity shadows enabled or not

**Comment by mateuskreuch** [comment]
Closing as it's not reproduceable and there's not enough information.
