### ISSUE TITLE
Enchanted Items turn white when on land.

### ISSUE THREAD

**Issue by fasicnated** [mateuskreuch/minecraft-miniature-shader#23]
**Describe the bug**
Enchanted items would appear plain white. When I go into the water, the items return to their normal texture?colour.

**To Reproduce**
1. Get an enchanted item.

**Expected behavior**
The item shouldn’t be white.

**System Information**
- Minecraft 1.21, Sodium 
- 2.13.2
- GTX 1050 TI

**Additional context**
Nothing

**Comment by mateuskreuch** [comment]
Can you post a screenshot?

**Comment by mateuskreuch** [comment]
Closing this as it seems to be [an issue on their part](https://github.com/FlashyReese/sodium-extra-fabric/issues/393), and fixing it on mine is not viable.
