### ISSUE TITLE
connected textures are reflective 

### ISSUE THREAD

**Issue by malovered** [mateuskreuch/minecraft-miniature-shader#25]
i'm using _Deep origins overlays by Devoneox_ resource pack that adds connected textures and all the custom textures end up being reflective, and also (or mb because of that) the lighting on them is off

1. use [_Deep Origins Overlays_](https://modrinth.com/resourcepack/deep-origins-overlays/) + [_Continuity mod_](https://modrinth.com/mod/continuity)
2. use _Miniature shaders_ + _Iris_

**Expected behavior**
It not happening (?)

**Screenshots**
reflections issue
![185_L3j8qOPwhD](https://github.com/user-attachments/assets/8a24dbae-2c7a-4bf5-96ff-1dd8404b822b)

lighting issue
![javaw_186_9jOJWfDYX9](https://github.com/user-attachments/assets/f140f3c5-3532-4747-a9df-73dda72636e5)

**System Information**

- minecraft 1.21
- fabric 0.16.0
- continuity v3.0.0-beta.5
- iris v.1.7.3
- Deep Origins Overlays RP

love the shader — been looking for something minimalistic like that — but that bug is pretty distracting
maybe add an option to choose which surfaces are gonna be reflective?, i'd like only water to be reflective

**Comment by mateuskreuch** [comment]
This is an issue with Deep Origins Overlays. They registered the sand overlays as translucent, instead of cutout_mipped.
