### ISSUE TITLE
Block entity fog missing

### ISSUE THREAD

**Issue by theDerpu** [mateuskreuch/minecraft-miniature-shader#29]
![image](https://github.com/user-attachments/assets/85638d15-c613-45f9-a297-49879bc8b683)
^ Example in water

![image](https://github.com/user-attachments/assets/40b24455-c3ea-46d5-9bab-c0a7017037d8)
^ Example with fog

**Comment by mateuskreuch** [comment]
Do you have any other mods? It works perfectly fine for me

**Comment by theDerpu** [comment]
sorry please ignore, edited the shader and was using the wrong one x_x
