### ISSUE TITLE
Decorated_pot in water = reflection is wrong

### ISSUE THREAD

**Issue by 1GodRage** [mateuskreuch/minecraft-miniature-shader#3]
**Describe the bug**
Decorated pot reflection is wrong.

**To Reproduce**
1. Place decorated pot in water
2. See error

**Expected behavior**
Reflection on water such as what have been done with boats with chest.

**Screenshots**
![image](https://github.com/mateuskreuch/minecraft-miniature-shader/assets/63362446/e773e723-6352-4b9d-92f2-2fac801efbcf)

**System Information**
- windows 10, Minecraft Java version 1.20.4 with experimental features on a Purpur server, Sodium + iris
- 2.4.3
- GPU nvidia RTX 3050 Ti Laptop

**Additional context**

**Comment by mateuskreuch** [comment]
Again, these are artifacts of Screen Space Reflections. You can see the same thing in the BSL shader or others which use the same technique:

![image_2023-12-27_150333214](https://github.com/mateuskreuch/minecraft-miniature-shader/assets/125627070/e64089ee-154c-4342-895d-8f6cab9d02e1)
