### ISSUE TITLE
[1.21.1] Minimum Water Texture Not Working on Iris 1.8 Release/Sodium 0.6

### ISSUE THREAD

**Issue by Lockehartt** [mateuskreuch/minecraft-miniature-shader#30]
**Describe the bug**
When switching from the Iris 1.8/Sodium 0.6 betas to the full releases, the 'Minimum Water Texture' feature appears to have stopped working. Other features like waves & color settings seem to still apply

**To Reproduce**
1. Install Iris 1.8 & Sodium 0.6 full releases
2. Enable Mini Shader
3. Load up world & find water

**Expected behavior**
Expected no changes to the water visuals from initial settings, since the default Min Water Texture was kept at 4.

**Screenshots**
![Min Water Res Iris 1 8 Beta](https://github.com/user-attachments/assets/6161dae0-d23f-4d38-8f85-ea28541283ba)
Before, running on Iris 1.8.0-beta-4 & Sodium 0.6.0-beta-2

![Min Water Res Iris 1 8 Full](https://github.com/user-attachments/assets/80666633-4acf-4397-93ae-d73380f77287)
After, running on Iris 1.8.0 & Sodium 0.6.0

**System Information**
- MC 1.21.1, Simply Optimized 4.2 with only these mods changed
- Shader v2.13.3
- Nvidia Geforce GTX 1660Ti

**Additional context**
Unsure if this is something that _you_ would have to fix, or if it's an Iris/Sodium issue, but just wanted to bring it up in case you could fix it!

**Comment by mateuskreuch** [comment]
I fixed the water texture, but shadows broke too and that's on them to fix.

**Comment by Lockehartt** [comment]
Gotcha, thanks for looking into it!
