### ISSUE TITLE
Black Boxes in the distance

### ISSUE THREAD

**Issue by zozogame1** [mateuskreuch/minecraft-miniature-shader#32]
**Describe the bug**
I see black boxes in the distance. They follow me when i move.

**To Reproduce**
Apply the shader. that's it.

**Expected behavior**
I though everything would be ok, but no.

**Screenshots**

![2024-12-14_11 28 30](https://github.com/user-attachments/assets/ebe43a9b-0a6b-4ace-bd46-0fb3c2bfd883)

**System Information**
I'm using 1.21.4, shader version 2.13.6. I'm using an intel UHD Graphics 610, with Linux Mint 22. 
Mods list : (note the file is too big so i took screenshots of the mods)
![Capture d’écran du 2024-12-14 11-38-22](https://github.com/user-attachments/assets/cb31800e-a0b7-4d4b-b537-9debed37261e)
![Capture d’écran du 2024-12-14 11-38-09](https://github.com/user-attachments/assets/e1053914-5491-4880-95ca-8422b49989ea)
![Capture d’écran du 2024-12-14 11-37-43](https://github.com/user-attachments/assets/643820da-c7af-4fa8-824b-d1cb57c0b417)
![Capture d’écran du 2024-12-14 11-37-28](https://github.com/user-attachments/assets/250b91cb-8ea3-444f-b3a9-04009d198d2a)
![Capture d’écran du 2024-12-14 11-37-07](https://github.com/user-attachments/assets/42c07751-43b6-4e44-9911-56f11acf3e64)

**Additional context**
I will provide the log file. (Note: I used other shaders to see if it was only with miniature shader and yes it is) :
[latest.log](https://github.com/user-attachments/files/18135492/latest.log)

**Comment by mateuskreuch** [comment]
The log has a bunch of errors that are impossible to occur normally, so it's probably a mod conflict. See if this happens with just Iris or Optifine, otherwise it'll probably be fixed by the culprit eventually.

**Comment by zozogame1** [comment]
fixed, it was with "raise the cloud"
