### ISSUE TITLE
Flowing water has different color with static water

### ISSUE THREAD

**Issue by HowardZHY** [mateuskreuch/minecraft-miniature-shader#6]
**Expected behavior**
The flowing water color should be same as normal water

**Screenshots**
![2024-01-04_22 41 25](https://github.com/mateuskreuch/minecraft-miniature-shader/assets/96782166/a8ce181b-e131-4142-9221-d8c2ae9b6301)

**System Information**
- 1.20.2 Iris 1.6.14
- 2.4.4

**Comment by HowardZHY** [comment]
WATER_BRIGHTNESS=0.5
WATER_WAVE_SPEED=1
WATER_A=0.8
OVERWORLD_FOG_MAX_SLIDER=0
WATER_B=2.0
ENABLE_FOG=false
CONTRAST=1.0
WATER_MIN_TEXTURE=-1

**Comment by mateuskreuch** [comment]
Can't reproduce. Are you using a resource pack by any chance?

![image_2024-01-04_182526747](https://github.com/mateuskreuch/minecraft-miniature-shader/assets/125627070/f8aa4624-a7f7-4183-9f22-8452d50bd35b)

**Comment by HowardZHY** [comment]
Oh yes, https://modrinth.com/resourcepack/simple-water/versions
